test: `npm run test` now works on each subdirectory (#2838)
We need to pass `--` to mark which parameters should be passed to the web-test-runner.

Without this commit:

    > test:web
    > web-test-runner testing-helpers

    Error: Could not find any test files with pattern(s): testing-helpers

With this commit, the tests run just fine.

Co-authored-by: Pascal Schilp <pascalschilp@gmail.com>